### ISSUE TITLE
Remove parentheses from arrow functions when passing one variable

### ISSUE THREAD

**Issue by jeroentvb** [DanielvandeVelde/web-app-from-scratch-18-19#2]
https://github.com/DanielvandeVelde/web-app-from-scratch-18-19/blob/e6a53b87b37a3b33236afeb3db3240f7a004564c/week1/public/js/app.js#L16

You can remove the parentheses from an arrow function if you are only passing one variable.
It would turn into this:

```js
data.forEach(beer => {
```

This also goes for this line:
https://github.com/DanielvandeVelde/web-app-from-scratch-18-19/blob/ac752e87bdb72c563740d58bf4197dff25d58a10/week1/public/js/app.js#L44

**Comment by DanielvandeVelde** [comment]
Good call,
I guess it makes more sense to remove them since it's a single variable.
Thanks
