### ISSUE TITLE
Avoid else

### ISSUE THREAD

**Issue by Arash217** [DanielvandeVelde/web-app-from-scratch-18-19#3]
https://github.com/DanielvandeVelde/web-app-from-scratch-18-19/blob/ac752e87bdb72c563740d58bf4197dff25d58a10/week1/public/js/app.js#L36

Using the "else" statement can make code more difficult to understand. Try to avoid it. Here's a [good article](http://blog.timoxley.com/post/47041269194/avoid-else-return-early) on how to avoid it.

**Comment by DanielvandeVelde** [comment]
Interesting article, never knew about this way of dealing with "if/else".
I applied the method to the code, thanks!
