### ISSUE TITLE
First build sub dom tree, then render HTML block once

### ISSUE THREAD

**Issue by joostf** [DanielvandeVelde/web-app-from-scratch-18-19#6]
https://github.com/DanielvandeVelde/web-app-from-scratch-18-19/blob/fa0992a77239e49cd48da3b440a323a8bd74cc61/week1/public/js/app.js#L44-L68

**Comment by DanielvandeVelde** [comment]
I found this part to be really difficult which really shows in that code.  
I read a lot more about how to build a proper DOM so I think I've done it correctly now.  
Please close this issue if that is the case. 
If I still lack something I would love to know how to do it properly.
