### ISSUE TITLE
Promisify XHR

### ISSUE THREAD

**Issue by joostf** [DanielvandeVelde/web-app-from-scratch-18-19#7]
https://github.com/DanielvandeVelde/web-app-from-scratch-18-19/blob/fa0992a77239e49cd48da3b440a323a8bd74cc61/week1/public/js/app.js#L4

**Comment by DanielvandeVelde** [comment]
Made it a promise.
I still need to provide correct error-handling so I will leave this issue open for now.

**Comment by DanielvandeVelde** [comment]
Created some sort of error handler
